"""Initial migration

Revision ID: 1cff66e6bb36
Revises: 
Create Date: 2025-11-16 21:04:18.459409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cff66e6bb36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'businesses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('social_profiles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('uq_profile_business_platform_handle', 'social_profiles', type_='unique')
    op.create_unique_constraint('uq_profile_user_platform_handle', 'social_profiles', ['user_id', 'platform', 'handle'])
    op.create_foreign_key(None, 'social_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_profiles', type_='foreignkey')
    op.drop_constraint('uq_profile_user_platform_handle', 'social_profiles', type_='unique')
    op.create_unique_constraint('uq_profile_business_platform_handle', 'social_profiles', ['business_id', 'platform', 'handle'])
    op.drop_column('social_profiles', 'user_id')
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'user_id')
    # ### end Alembic commands ###

