"""add_affiliate_links_table

Revision ID: 75381ff87526
Revises: b2c3d4e5f6a7
Create Date: 2025-11-25 19:59:31.859938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75381ff87526'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('affiliate_program', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('payout_type', sa.Enum('cpc', 'cpa', 'rev_share', 'percent', 'fixed', name='payouttype'), nullable=False),
    sa.Column('commission_rate', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('seo_keywords', sa.Text(), nullable=True),
    sa.Column('estimated_conversion_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('preferred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('campaigns', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('campaigns', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('locations', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('media_assets', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('oauth_states', 'code_verifier',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('social_profiles', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'connected'::character varying"))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('social_profiles', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'connected'::character varying"))
    op.alter_column('oauth_states', 'code_verifier',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('media_assets', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('locations', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('campaigns', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('campaigns', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('affiliate_links')
    # ### end Alembic commands ###

