
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-lb-marketing}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
